name: admin_panel
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6

  firebase_core: ^2.16.0
  cloud_firestore: ^4.9.2
  firebase_storage: ^11.2.7

  get: ^4.6.6

  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.2.1
  google_fonts:
  fluttertoast: ^8.2.2
  intl: ^0.18.1
  flutter_svg: ^2.0.7

  syncfusion_flutter_charts: ^23.1.38

  geolocator:
  country_code_picker: ^3.0.0
  geoflutterfire2: ^2.3.15
  location_picker_flutter_map: ^1.2.2

  image_picker: ^1.0.4
  syncfusion_flutter_datagrid: ^23.1.38

  cached_network_image: ^3.3.0

  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.3
  flutter_test: 
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/

